# Generated by Django 5.1.3 on 2024-11-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto_pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
