# Generated by Django 5.1.3 on 2024-12-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto_pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productopedido',
            name='precio_unitario',
        ),
    ]
