# Generated by Django 5.1.3 on 2024-11-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto_pedido', '0002_productopedido_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
