# Generated by Django 5.1.3 on 2024-12-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto_pedido', '0002_remove_productopedido_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
