# Generated by Django 5.1.3 on 2024-12-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=100)),
                ('codigo_postal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
    ]
