# Generated by Django 5.1.3 on 2024-12-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Direccion', '0003_alter_direccion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(default='Calle', max_length=200),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(default='Ciudad', max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(default='Pais', max_length=100),
        ),
    ]
