# Generated by Django 5.1.3 on 2024-12-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Direccion', '0004_alter_direccion_calle_alter_direccion_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
