# Generated by Django 5.1.3 on 2024-12-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Direccion', '0005_alter_direccion_codigo_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.IntegerField(default=0),
        ),
    ]
