# Generated by Django 5.1.3 on 2024-11-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('EP', 'En proceso'), ('E', 'Enviado'), ('ET', 'Entregado'), ('C', 'Cancelado')], default='P', max_length=2)),
            ],
        ),
    ]
