# Generated by Django 5.1.3 on 2024-12-06 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('EP', 'En proceso'), ('E', 'Enviado'), ('ET', 'Entregado'), ('C', 'Cancelado')], default='P', max_length=2)),
                ('metodo_pago', models.CharField(choices=[('T', 'Tarjeta de Crédito'), ('C', 'Contra Reembolso')], default='T', max_length=2)),
                ('codigo_rastreo', models.CharField(blank=True, max_length=16, null=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
