# Generated by Django 5.1.3 on 2024-11-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0003_alter_pedido_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
