# Generated by Django 5.1.3 on 2024-11-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0005_alter_pedido_direccion'),
        ('Pedido', '0005_alter_pedido_usuario'),
    ]

    operations = [
    ]