# Generated by Django 5.1.3 on 2024-11-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0007_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('T', 'Tarjeta de Crédito'), ('C', 'Contra Reembolso')], default='T', max_length=2),
        ),
    ]
