# Generated by Django 5.1.3 on 2024-12-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0008_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_rastreo',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
