# Generated by Django 5.1.3 on 2024-12-05 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0009_pedido_codigo_rastreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
