# Generated by Django 5.1.3 on 2024-12-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0010_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
