# Generated by Django 5.1.3 on 2024-12-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0011_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
