# Generated by Django 5.1.3 on 2024-11-28 18:58

from django.db import migrations
from django.contrib.auth.models import User


def carga_inicial(apps, schema_editor):
    User.objects.create_user(
        username='officepack',
        email='officepack@gmail.com',
        password='officepack4dm1n'
    )

    

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(carga_inicial),
    ]
