# Generated by Django 5.1.3 on 2024-12-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedido', '0001_initial'),
        ('Producto', '0002_carga_inicial'),
        ('Producto_pedido', '0001_initial'),
    ]

    operations = [
    ]
