# Generated by Django 5.1.3 on 2024-12-02 10:54

from django.db import migrations
from django.contrib.auth.models import User

def carga_inicial(apps, schema_editor):
    User.objects.create_user(
        username='officepack',
        email='officepack@gmail.com',
        password='4dm1n',
        is_staff=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(carga_inicial),
    ]
