# Generated by Django 5.1.3 on 2024-11-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='material',
            field=models.CharField(default='Material no especificado', max_length=255),
        ),
    ]
