# Generated by Django 5.1.3 on 2024-11-27 19:53

from django.db import migrations

def carga_inicial(apps, schema_editor):
    Producto = apps.get_model('Producto', 'Producto')

    productos = [
        {'nombre': 'Silla Oficina Ergonomica', 'precio': 120.50, 'cantidad_almacen': 200, 'fabricante': 'OficinaPlus', 'material': 'Tela y Plástico', 'tipo': 'MUEBLE', 'foto': 'https://static.sillaoficina365.es/82561-product_list/silla-oficina-ergonomica-con-reposapies-balance-pro-brazos-3d.jpg'},
        {'nombre': 'Silla de Oficina Herman Miller Aeron', 'precio': 1200.00, 'cantidad_almacen': 40, 'fabricante': 'Herman Miller', 'material': 'Malla y Metal', 'tipo': 'MUEBLE', 'foto': 'https://www.oficinasmontiel.com/75736-large_default/silla-ergonomica-aeron-de-herman-miller-talla-b-o-c.jpg'},
        {'nombre': 'Estufa Eléctrica DeLonghi', 'precio': 179.99, 'cantidad_almacen': 70, 'fabricante': 'DeLonghi', 'material': 'Metal y Plástico', 'tipo': 'ELECTRONICO', 'foto': 'https://www.delonghi.com/medias/en-Category-Sort-portable-heaters-TRRS0920-desk.jpg?context=bWFzdGVyfHJvb3R8MjQ0MzJ8aW1hZ2UvanBlZ3xhR0V4TDJoak1TODVOakkyTmpVd01UZ3hOall5TDJWdVgwTmhkR1ZuYjNKNUxWTnZjblJmY0c5eWRHRmliR1V0YUdWaGRHVnljeTFVVWxKVE1Ea3lNQzFrWlhOckxtcHdad3xhMjk1NjYwZWM4NDQwNWJjOGU3ZTQxYjYxMTEwZmM0MmVlZWI4OWU1YzNjZTQyMTg3ZDYyNDk3Zjg2MmFiMDI5'},    
        {'nombre': 'Silla de oficina ergonómica', 'precio': 120.00, 'cantidad_almacen': 150, 'fabricante': 'OficinaPlus', 'material': 'Tela y Plástico', 'tipo': 'MUEBLE', 'foto': 'https://www.ofiprix.com/292701/silla-ergonomica-de-oficina-con-reposacabezas-brazos-3d-red-goliath.jpg'},
        {'nombre': 'Mesa de comedor de vidrio', 'precio': 250.00, 'cantidad_almacen': 0, 'fabricante': 'Muebles Modernos', 'material': 'Vidrio y Metal', 'tipo': 'MUEBLE', 'foto': 'https://d.media.kavehome.com/image/upload/w_900,c_fill,ar_0.8,g_auto,f_auto/v1721897031/products/C436C07_1V01.png'},
        {'nombre': 'Lámpara de mesa LED', 'precio': 40.00, 'cantidad_almacen': 0, 'fabricante': 'LuzTech', 'material': 'Metal y Plástico', 'tipo': 'ELECTRONICO', 'foto': 'https://www.manicura24.es/biblioteca/images_manicura/8707-Lampara-de-mesa-LED-02.jpg'},
        {'nombre': 'Escritorio de madera para oficina', 'precio': 180.00, 'cantidad_almacen': 0, 'fabricante': 'Muebles Casa', 'material': 'Madera', 'tipo': 'MUEBLE', 'foto': 'https://aulamobel.com/wp-content/uploads/2018/02/Mesa-para-oficina-Panel1.jpg'},
        {'nombre': 'Escritorio de madera', 'precio': 180.00, 'cantidad_almacen': 80, 'fabricante': 'Muebles Casa', 'material': 'Madera', 'tipo': 'MUEBLE', 'foto': 'https://cdn.manomano.com/images/images_products/743659/P/28453116_1.jpg'},        
        {'nombre': 'Lámpara de pie moderna', 'precio': 75.00, 'cantidad_almacen': 0, 'fabricante': 'LuzHome', 'material': 'Metal', 'tipo': 'ELECTRONICO', 'foto': 'https://www.muebleslluesma.com/400992-large_default/lampara-pie-zero11-lumen-center.jpg'},
        {'nombre': 'Sofá de 3 plazas', 'precio': 450.00, 'cantidad_almacen': 40, 'fabricante': 'SofáExpress', 'material': 'Tela y Madera', 'tipo': 'MUEBLE', 'foto': 'https://tuttoconfortmurcia.com/wp-content/uploads/2023/09/sofa-lineal-asientos-relax-nerea-oferta.jpg'},
        
        {'nombre': 'Mesa de café de vidrio', 'precio': 120.00, 'cantidad_almacen': 60, 'fabricante': 'Muebles Modernos', 'material': 'Vidrio y Metal', 'tipo': 'MUEBLE', 'foto': 'https://medias.maisonsdumonde.com/images/ar_1:1,c_pad,f_auto,q_auto,w_732/v1/mkp/M24128355_2/mesa-de-cafe-en-vidrio-roble-80x80-h40-cm.jpg'},
        {'nombre': 'Estante de pared de madera', 'precio': 60.00, 'cantidad_almacen': 150, 'fabricante': 'DecoraHome', 'material': 'Madera', 'tipo': 'MUEBLE', 'foto': 'https://kasasdecoracion.com/12226-large_default/estante-pared-merapi-madera-con-costados.jpg'},
        {'nombre': 'Silla de cuero', 'precio': 350.00, 'cantidad_almacen': 0, 'fabricante': 'Muebles Casa', 'material': 'Cuero', 'tipo': 'MUEBLE', 'foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwiJ3Fhpf7FttqxwKOAA19aFtIW12bD7D4OA&s'},
        {'nombre': 'Mesa de café de cristal', 'precio': 120.00, 'cantidad_almacen': 0, 'fabricante': 'Muebles Modernos', 'material': 'Vidrio y Metal', 'tipo': 'MUEBLE', 'foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv0hIz5EbRZ08Z7O41G9Z8B0zni3MxHFsP0g&s'},
        {'nombre': 'Mesa de trabajo para oficina', 'precio': 200.00, 'cantidad_almacen': 90, 'fabricante': 'OficinaPlus', 'material': 'Madera', 'tipo': 'MUEBLE', 'foto': 'https://laoficinaonline.es/10204-home_default/mesa-escritorio-amba-de-kesta.jpg'},
        {'nombre': 'Mesa de comedor extensible', 'precio': 250.00, 'cantidad_almacen': 0, 'fabricante': 'Casa Muebles', 'material': 'Madera', 'tipo': 'MUEBLE', 'foto': 'https://cdn.sklum.com/es/wk/3061676/mesa-de-comedor-extensible-en-madera-de-acacia-160-210x90-cm-tenay.jpg?cf-resize=gallery'},
        {'nombre': 'Silla plegable', 'precio': 40.00, 'cantidad_almacen': 120, 'fabricante': 'Jardín & Relax', 'material': 'Plástico', 'tipo': 'MUEBLE', 'foto': 'https://d.media.kavehome.com/image/upload/v1709569519/products/J0700006JJ12_1V01.jpg'},
        {'nombre': 'Lámpara de escritorio con regulador', 'precio': 35.00, 'cantidad_almacen': 200, 'fabricante': 'LuzTech', 'material': 'Plástico', 'tipo': 'ELECTRONICO', 'foto': 'https://medias.maisonsdumonde.com/images/f_auto,q_auto,w_732/v1/mkp/M23135986_1/lampara-de-escritorio-led-con-bateria-e-intensidad-regulable-38x34x15.jpg'},
        {'nombre': 'Lámpara de techo de cristal', 'precio': 120.00, 'cantidad_almacen': 80, 'fabricante': 'LuzHome', 'material': 'Cristal y Metal', 'tipo': 'ELECTRONICO', 'foto': 'https://www.tiendason.es/media/catalog/product/cache/9db3b172fc93033b2db8734cdfbc7142/1/3/135110.jpg'},
        {'nombre': 'Espejo de cuerpo entero', 'precio': 150.00, 'cantidad_almacen': 100, 'fabricante': 'DecorHome', 'material': 'Madera y Vidrio', 'tipo': 'DECORACION', 'foto': 'https://www.centroespejos.com/28975-large_default/espejo-de-pared-cuerpo-entero-marco-negro.jpg'},
        
        {'nombre': 'Alfombra de sala', 'precio': 120.00, 'cantidad_almacen': 0, 'fabricante': 'DecoraHome', 'material': 'Algodón', 'tipo': 'DECORACION', 'foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkwCtUCoaSToNWyLR-pGWostm16taxNHkSzw&s'},
        {'nombre': 'Estanterías de cristal', 'precio': 180.00, 'cantidad_almacen': 90, 'fabricante': 'Muebles Kids', 'material': 'Madera', 'tipo': 'MUEBLE', 'foto': 'https://mueblesparamicasa.es/8345-large_default/estanteria-de-cristal-okay.jpg'},
        {'nombre': 'Lámpara de pie clásica', 'precio': 85.00, 'cantidad_almacen': 60, 'fabricante': 'LuzHome', 'material': 'Metal', 'tipo': 'ELECTRONICO', 'foto': 'https://www.chloesweethome.com/33565-large_default/lampara-de-pie-clasica-magma-dorada.jpg'},
        {'nombre': 'Mueble para TV de madera', 'precio': 200.00, 'cantidad_almacen': 70, 'fabricante': 'Muebles Modernos', 'material': 'Madera', 'tipo': 'MUEBLE', 'foto': 'https://i.etsystatic.com/16086164/r/il/5917ab/3764492513/il_570xN.3764492513_p2mb.jpg'},
        {'nombre': 'Espejo redondo moderno', 'precio': 100.00, 'cantidad_almacen': 200, 'fabricante': 'DecorArt', 'material': 'Madera y Cristal', 'tipo': 'DECORACION', 'foto': 'https://m.media-amazon.com/images/I/61IQ+jpReUL.jpg'},
        {'nombre': 'Mesa de centro estilo rústico', 'precio': 180.00, 'cantidad_almacen': 100, 'fabricante': 'Muebles Rústicos', 'material': 'Madera', 'tipo': 'MUEBLE', 'foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQx1ELynnOQ2lFazXbFmi7fZf5g7E17EpKg6w&s'},
        {'nombre': 'Lámpara de sobremesa vintage', 'precio': 45.00, 'cantidad_almacen': 150, 'fabricante': 'LuzVintage', 'material': 'Metal', 'tipo': 'ELECTRONICO', 'foto': 'https://compratuled.es/6354-large_default/comprar-lampara-de-mesa-vintage-banker-verde.jpg'},
        {'nombre': 'Silla de hierro', 'precio': 120.00, 'cantidad_almacen': 100, 'fabricante': 'Jardín & Relax', 'material': 'Hierro', 'tipo': 'MUEBLE', 'foto': 'https://www.ideearredo.com/9153-large_default/silla-de-jardin-de-hierro-apilable-liri-sin-brazos.jpg'},
        {'nombre': 'Lámpara vintage', 'precio': 45.00, 'cantidad_almacen': 0, 'fabricante': 'LuzVintage', 'material': 'Metal', 'tipo': 'ELECTRONICO', 'foto': 'https://luzvintage.es/12336-thickbox_default/lampara-vintage-mesa-pantalla-cupula-flecos-dalmar.jpg'},
        {'nombre': 'Sofá de 4 piezas', 'precio': 800.00, 'cantidad_almacen': 50, 'fabricante': 'SofáExpress', 'material': 'Tela y Madera', 'tipo': 'MUEBLE', 'foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWg-F7kUnXI1Duo_DcmC15ZCJ0b_XtYC6_qA&s'},
        
        {'nombre': 'Mesa de comedor de mármol', 'precio': 600.00, 'cantidad_almacen': 30, 'fabricante': 'Mármol & Madera', 'material': 'Mármol', 'tipo': 'MUEBLE', 'foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqFg8hgzeXHsBQg9J6_gc2x08wvZMaR8Sltg&s'},
        {'nombre': 'Lámpara colgante', 'precio': 80.00, 'cantidad_almacen': 200, 'fabricante': 'LuzTech', 'material': 'Metal', 'tipo': 'ELECTRONICO', 'foto': 'https://kosiluz.es/23345-large_default/gran-lampara-colgante-multiple-con-tubo-de-vidrio-poggio.jpg'},
        {'nombre': 'Escritorio para computadora', 'precio': 170.00, 'cantidad_almacen': 120, 'fabricante': 'OficinaPro', 'material': 'Madera', 'tipo': 'MUEBLE', 'foto': 'https://media.adeo.com/mkp/7f17359c28ee8ef698e1087d1a4e1977/media.jpg?width=3000&height=3000&format=jpg&quality=80&fit=bounds'},
        {'nombre': 'Alfombra de sala grande', 'precio': 120.00, 'cantidad_almacen': 150, 'fabricante': 'DecoraHome', 'material': 'Algodón', 'tipo': 'DECORACION', 'foto': 'https://img.joomcdn.net/323222e5a362671c94429be322d613fe2b3295f4_original.jpeg'},
        {'nombre': 'Cojines decorativos', 'precio': 15.00, 'cantidad_almacen': 500, 'fabricante': 'TextilDecor', 'material': 'Algodón', 'tipo': 'DECORACION', 'foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8ijAclnuwMlGFWIQCH9aDQjoDnEhnimMm3A&s'},
        {'nombre': 'Silla de comedor tapizada', 'precio': 110.00, 'cantidad_almacen': 180, 'fabricante': 'Muebles Casa', 'material': 'Tela y Madera', 'tipo': 'MUEBLE', 'foto': 'https://www.kionadecoracion.com/222689-thickbox_default/silla-de-comedor-queen-tapizada-en-tela-y-patas-metalicas-en-acabado-madera.jpg'},
        {'nombre': 'Mesa de centro de mármol', 'precio': 550.00, 'cantidad_almacen': 45, 'fabricante': 'Mármoles & Maderas', 'material': 'Mármol', 'tipo': 'MUEBLE', 'foto': 'https://www.thedezignerconceptstore.com/cdn/shop/products/mesademarmoll_800x.jpg?v=1648068091'},
        {'nombre': 'Lámpara de mesa de cerámica', 'precio': 50.00, 'cantidad_almacen': 220, 'fabricante': 'LuzArte', 'material': 'Cerámica y Metal', 'tipo': 'ELECTRONICO', 'foto': 'https://www.lauraashley.es/29575-large_default/lampara-mesa-heathfield-ceramica.jpg'},
        {'nombre': 'Silla tapizada de terciopelo', 'precio': 200.00, 'cantidad_almacen': 70, 'fabricante': 'SillasElegantes', 'material': 'Terciopelo y Madera', 'tipo': 'MUEBLE', 'foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsEb92z0EU0Z7IwFxo6bINN_kqZUqhs3tY_w&s'},
        {'nombre': 'Lámpara de pie de diseño', 'precio': 110.00, 'cantidad_almacen': 50, 'fabricante': 'Luz Diseño', 'material': 'Metal', 'tipo': 'ELECTRONICO', 'foto': 'https://albertogarciadisenointerior.com/wp-content/uploads/2022/03/lampara-pie-hinoo-aromas-del-campo-4.jpg'},
        
        {'nombre': 'Espejo envejecido', 'precio': 40.00, 'cantidad_almacen': 300, 'fabricante': 'DecoraHome', 'material': 'Vidrio', 'tipo': 'DECORACION', 'foto': 'https://iglutiendas.com/8423-large_default/espejo-envejecido-62-x-82-cm.jpg'},
        {'nombre': 'Silla de oficina ejecutiva', 'precio': 200.00, 'cantidad_almacen': 100, 'fabricante': 'OficinaPro', 'material': 'Cuero', 'tipo': 'MUEBLE', 'foto': 'https://aulamobel.com/wp-content/uploads/2018/03/Silla-oficina-Tirana.jpg'},
        {'nombre': 'Sofá modular de 4 piezas', 'precio': 800.00, 'cantidad_almacen': 0, 'fabricante': 'SofáExpress', 'material': 'Tela y Madera', 'tipo': 'MUEBLE', 'foto': 'https://due-home.com/42068-producto_zoom/sofa-modular-4-plazas-con-brazos-cubiq.jpg'},
        {'nombre': 'Lámpara de pie', 'precio': 85.00, 'cantidad_almacen': 0, 'fabricante': 'LuzHome', 'material': 'Metal', 'tipo': 'ELECTRONICO', 'foto': 'https://luzvintage.es/img/p/1/3/7/3/7/13737.jpg'},
        {'nombre': 'Mesa de comedor redonda', 'precio': 300.00, 'cantidad_almacen': 80, 'fabricante': 'Muebles Modernos', 'material': 'Madera', 'tipo': 'MUEBLE', 'foto': 'https://d.media.kavehome.com/image/upload/w_900,c_fill,ar_0.8,g_auto,f_auto/v1721897075/products/CC6021M46_1V01.png'},
        {'nombre': 'Lámpara de techo moderna', 'precio': 130.00, 'cantidad_almacen': 90, 'fabricante': 'LuzHome', 'material': 'Metal y Cristal', 'tipo': 'ELECTRONICO', 'foto': 'https://www.decoracionbeltran.com/51753-superlarge_default/lampara-moderna-de-techo-coleccion-molly-cromo-schuller.jpg'},
        {'nombre': 'Sofá de 2 plazas', 'precio': 350.00, 'cantidad_almacen': 120, 'fabricante': 'SofáExpress', 'material': 'Tela', 'tipo': 'MUEBLE', 'foto': 'https://topmueble.com/11832/sofa-de-2-plazas-athenea-bronx.jpg'},
        {'nombre': 'Lámpara de pie industrial', 'precio': 140.00, 'cantidad_almacen': 80, 'fabricante': 'LuzVintage', 'material': 'Metal', 'tipo': 'ELECTRONICO', 'foto': 'https://medias.maisonsdumonde.com/image/upload/ar_1:1,c_fill,f_auto,q_auto,w_732/v1/img/lampara-de-pie-industrial-de-metal-negro-alt-168-1000-8-40-177488_2.jpg'},
        {'nombre': 'Mesa auxiliar de madera', 'precio': 60.00, 'cantidad_almacen': 200, 'fabricante': 'Muebles Casa', 'material': 'Madera', 'tipo': 'MUEBLE', 'foto': 'https://mobel6000.com/47714-ficha/mesa-auxiliar-de-madera-maciza-luxu-frajumar.jpg'},
        {'nombre': 'Lámpara de techo de cristal', 'precio': 120.00, 'cantidad_almacen': 0, 'fabricante': 'LuzHome', 'material': 'Cristal y Metal', 'tipo': 'ELECTRONICO', 'foto': 'https://www.tiendason.es/media/catalog/product/cache/9db3b172fc93033b2db8734cdfbc7142/1/3/135110.jpg'},
        
        {'nombre': 'Alfombra de lana', 'precio': 160.00, 'cantidad_almacen': 100, 'fabricante': 'TextilDecor', 'material': 'Lana', 'tipo': 'DECORACION', 'foto': 'https://m.media-amazon.com/images/I/61dzU4v8YIL._AC_UF350,350_QL80_.jpg'},
        {'nombre': 'Lámpara colgante de hierro', 'precio': 90.00, 'cantidad_almacen': 150, 'fabricante': 'LuzArte', 'material': 'Hierro', 'tipo': 'ELECTRONICO', 'foto': 'https://www.dekoratu.com/14986/lampara-colgante-de-hierro-color-negro-estilo-contemporaneo-md5769-bk.jpg'},
        {'nombre': 'Silla de comedor moderna', 'precio': 150.00, 'cantidad_almacen': 180, 'fabricante': 'Muebles Casa', 'material': 'Metal y Tela', 'tipo': 'MUEBLE', 'foto': 'https://demarques.es/37905-home_default/silla-ryta-tapizado-tela-belfast.jpg'},
        {'nombre': 'Mesa de centro de roble', 'precio': 500.00, 'cantidad_almacen': 60, 'fabricante': 'Muebles Rústicos', 'material': 'Roble', 'tipo': 'MUEBLE', 'foto': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlQFRRkX-Ak7dS1gbkoL340Y4Bd2o5IiDd7g&s'},
    ]


    for producto in productos:
        Producto.objects.create(**producto)

class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(carga_inicial),
    ]

