# Generated by Django 4.2.7 on 2024-11-26 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_carga_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
    ]
