# Generated by Django 5.1.3 on 2024-12-06 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_carga_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
