# Generated by Django 4.2.7 on 2024-11-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_producto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('MUEBLE', 'Mueble'), ('ELECTRONICO', 'Electronico'), ('DECORACION', 'Decoracion')], default='MUEBLE', max_length=20),
        ),
    ]
