# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import unittest

class TestTestuicestacatalogo():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testuicestacatalogo(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1550, 838)
    self.driver.find_element(By.CSS_SELECTOR, "header").click()
    self.driver.find_element(By.LINK_TEXT, "Catálogo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-item:nth-child(1) > .add-to-cart:nth-child(2) > button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-item:nth-child(2) > .product-info").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-item:nth-child(2) > .add-to-cart:nth-child(2) > button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-item:nth-child(3) > .add-to-cart:nth-child(2) > button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-item:nth-child(4) > .add-to-cart:nth-child(2) > button").click()
    self.driver.find_element(By.LINK_TEXT, "Cesta").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .cart-form:nth-child(2) > .cart-button").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .cart-form:nth-child(2) > .cart-button").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .cart-form:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .cart-form:nth-child(2) > .cart-button").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .cart-form:nth-child(2) > .cart-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .cart-form:nth-child(2) > .cart-button")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .cart-form:nth-child(1) > .cart-button").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .cart-form:nth-child(1) > .cart-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .cart-form:nth-child(1) > .cart-button")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .cart-link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-form:nth-child(1) > .cart-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-form:nth-child(1) > .cart-button").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Catálogo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-item:nth-child(2) img").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
  
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
