# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import unittest

class TestTestuiadmin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testuiadmin(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1550, 838)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("officepack@gmail.com")
    self.driver.find_element(By.ID, "id_password").send_keys("4dm1n")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Gestionar Productos").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-item:nth-child(3) .gestionar_productos > button").click()
    self.driver.find_element(By.ID, "id_precio").send_keys("39.98")
    self.driver.find_element(By.ID, "id_precio").click()
    self.driver.find_element(By.ID, "id_precio").send_keys("39.97")
    self.driver.find_element(By.ID, "id_precio").click()
    element = self.driver.find_element(By.ID, "id_precio")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "id_precio").send_keys("39.96")
    self.driver.find_element(By.ID, "id_precio").click()
    self.driver.find_element(By.ID, "id_precio").send_keys("39.95")
    self.driver.find_element(By.ID, "id_precio").click()
    element = self.driver.find_element(By.ID, "id_precio")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "id_cantidad_almacen").send_keys("68")
    self.driver.find_element(By.ID, "id_cantidad_almacen").click()
    self.driver.find_element(By.ID, "id_cantidad_almacen").send_keys("67")
    self.driver.find_element(By.ID, "id_cantidad_almacen").click()
    element = self.driver.find_element(By.ID, "id_cantidad_almacen")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "id_cantidad_almacen").send_keys("66")
    self.driver.find_element(By.ID, "id_cantidad_almacen").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.LINK_TEXT, "Gestionar Pedidos").click()
    self.driver.find_element(By.LINK_TEXT, "Gestionar Usuarios").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()