# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import unittest

class TestTestuicompra():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testuicompra(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1550, 838)
    self.driver.find_element(By.LINK_TEXT, "Catálogo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-item:nth-child(3) > .add-to-cart:nth-child(2) > button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-item:nth-child(2) > .add-to-cart:nth-child(2) > button").click()
    self.driver.find_element(By.LINK_TEXT, "Ver cesta").click()
    self.driver.find_element(By.LINK_TEXT, "Realizar Pedido").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("ad@example.com")
    self.driver.find_element(By.ID, "direccion").click()
    self.driver.find_element(By.ID, "direccion").send_keys("Calle Real")
    self.driver.find_element(By.ID, "metodo_pago").click()
    dropdown = self.driver.find_element(By.ID, "metodo_pago")
    dropdown.find_element(By.XPATH, "//option[. = 'Contra Reembolso']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
    self.driver.find_element(By.ID, "submit-button").click()
    self.driver.find_element(By.LINK_TEXT, "Volver al inicio").click()
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
  
